import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import { ModeToggle } from "@/components/mode-toggle";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            font.className,
            "bg-[#f0f4f7] dark:bg-[#000000] text-zinc-700 dark:text-zinc-200"
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            storageKey="cenizasai-theme"
          >
            {children}
            <div className="fixed top-2 right-2 hide-on-print">
              <ModeToggle />
            </div>
          </ThemeProvider>
        </body>
      </html>
  );
}
